### ISSUE TITLE
Compilation failed on archlinux

### ISSUE THREAD

**Issue by SnipyJulmy** [pop-team/pop-cpp#5]
Hi,

I have an error when compiling on my laptop :
`‘accumulate’ is not a member of ‘std’
     prots = std::accumulate(list.begin(), list.end(), std::string()`

and I resolve this by adding
`#include <numeric>`

in top of the lib/core/combox_factory.cc file

Have a nice Day !

**Comment by wichtounet** [comment]
Hi, 

Thanks for reporting this. 

Sorry about this. This is a known issue and has been already fixed in 877cf42. This will be included in the future releases of POP. 

Best regards
Baptiste
